version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Unit tests
          command: yarn test:ci

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
