#!/bin/sh
if [ "$TRAVIS_BRANCH" = "master" ]; then
  export BOOKLYER_FIREBASE_API_KEY=$PROD_FIREBASE_API_KEY
  export BOOKLYER_FIREBASE_AUTH_DOMAIN=$PROD_FIREBASE_AUTH_DOMAIN
  export BOOKLYER_FIREBASE_DATABASE_URL=$PROD_FIREBASE_DATABASE_URL
  export BOOKLYER_FIREBASE_MESSAGING_SENDER_ID=$PROD_FIREBASE_MESSAGING_SENDER_ID
  export BOOKLYER_FIREBASE_PROJECT_ID=$PROD_FIREBASE_PROJECT_ID
  export BOOKLYER_FIREBASE_STORAGE_BUCKET=$PROD_FIREBASE_STORAGE_BUCKET
else
  export BOOKLYER_FIREBASE_API_KEY=$STAGING_FIREBASE_API_KEY
  export BOOKLYER_FIREBASE_AUTH_DOMAIN=$STAGING_FIREBASE_AUTH_DOMAIN
  export BOOKLYER_FIREBASE_DATABASE_URL=$STAGING_FIREBASE_DATABASE_URL
  export BOOKLYER_FIREBASE_MESSAGING_SENDER_ID=$STAGING_FIREBASE_MESSAGING_SENDER_ID
  export BOOKLYER_FIREBASE_PROJECT_ID=$STAGING_FIREBASE_PROJECT_ID
  export BOOKLYER_FIREBASE_STORAGE_BUCKET=$STAGING_FIREBASE_STORAGE_BUCKET
fi
export BOOKLYER_FIREBASE_TEMP_OWNER_ID=$FIREBASE_TEMP_OWNER_ID
yarn build
